INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('1', 'Japan', 'Tokyo', '35200000', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('2', 'China', 'Beijing', '13955000', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('3', 'United Kingdom', 'London', '8787892', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('4', 'Germany', 'Berlin', '3670622', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('5', 'Spain', 'Madrid', '3141991	', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('6', 'Italy', 'Rome', '2879215	', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('7', 'France', 'Paris', '2244000', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('8', 'Romania', 'Bucharest', '2106144', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('9', 'Austria', 'Vienna', '1877836', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('10', 'Hungary', 'Budapest', '1759407', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('11', 'Poland', 'Warsaw', '1753977', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('12', 'Czech Republic', 'Prague', '1280508', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('13', 'Bulgaria', 'Sofia', '1260120', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('14', 'Belgium', 'Brussels', '1187890', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('15', 'Sweden', 'Stockholm', '947380	', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('16', 'Netherlands', 'Amsterdam', '848861', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('17', 'Croatia', 'Zagreb', '806920	', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('18', 'Ukraine', 'Kyiv', '42248598', '1');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('19', 'Poland', 'Krakow', '766739', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('20', 'Spain', 'Valencia', '790201', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('21', 'Italy', 'Naples', '970185', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('22', 'Germany', 'Cologne', '1060582', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('23', 'United Kingdom', 'Birmingham', '1111307', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('24', 'Italy', 'Milan', '1368590', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('25', 'Germany', 'Munich', '1542860', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('26', 'Spain', 'Barcelona', '1608746	', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('27', 'Germany', 'Hamburg', '1787408', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('28', 'China', 'Hong Kong', '7055000', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('29', 'Japan', 'Osaka', '17320000', '0');
INSERT INTO `homework`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('30', 'China', 'Shanghai', '18400000', '0');

UPDATE `homework`.`countryinfo` SET `CountryName`='Poland', `CityName`='Wroclaw', `Population`='637683	' WHERE `city_id`='30';
UPDATE `homework`.`countryinfo` SET `CountryName`='Poland', `CityName`='Radomsko', `Population`='49073' WHERE `city_id`='29';
UPDATE `homework`.`countryinfo` SET `CountryName`='Poland', `CityName`='Legionowo', `Population`='20836' WHERE `city_id`='28';
UPDATE `homework`.`countryinfo` SET `CountryName`='Ukraine', `CityName`='Zaporizhia', `Population`='815256' WHERE `city_id`='27';
UPDATE `homework`.`countryinfo` SET `CountryName`='Ukraine', `CityName`='Lviv', `Population`='732818' WHERE `city_id`='26';
UPDATE `homework`.`countryinfo` SET `CountryName`='Ukraine', `CityName`='Bucha', `Population`='28533' WHERE `city_id`='25';
UPDATE `homework`.`countryinfo` SET `CountryName`='Ukraine', `CityName`='Khust', `Population`='29080' WHERE `city_id`='24';
